---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        htpasswd_mode: "640"
  playbooks:
    prepare: ../prepare.yml
    converge: ../converge.yml
verifier:
  name: ansible
